# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Qt/Qt5.11.1/5.11.1/mingw53_32/bin/fixateGUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FixateUI(object):
    def setupUi(self, FixateUI):
        FixateUI.setObjectName("FixateUI")
        FixateUI.resize(620, 710)
        FixateUI.setMinimumSize(QtCore.QSize(620, 710))
        FixateUI.setFocusPolicy(QtCore.Qt.StrongFocus)
        FixateUI.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        FixateUI.setWindowTitle("Fixate")
        FixateUI.setWindowOpacity(1.0)
        FixateUI.setToolTip("")
        FixateUI.setStatusTip("Fixate")
        FixateUI.setWhatsThis("Fixate")
        FixateUI.setAccessibleName("Fixate")
        FixateUI.setAccessibleDescription("")
        FixateUI.setAutoFillBackground(False)
        FixateUI.setWindowFilePath("")
        FixateUI.setInputMethodHints(QtCore.Qt.ImhNone)
        FixateUI.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.MainWindow = QtWidgets.QWidget(FixateUI)
        self.MainWindow.setObjectName("MainWindow")
        self.gridLayout = QtWidgets.QGridLayout(self.MainWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.ActiveTest = QtWidgets.QLabel(self.MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.ActiveTest.sizePolicy().hasHeightForWidth())
        self.ActiveTest.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.ActiveTest.setFont(font)
        self.ActiveTest.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.ActiveTest.setToolTip("")
        self.ActiveTest.setStatusTip("")
        self.ActiveTest.setWhatsThis("")
        self.ActiveTest.setAccessibleName("")
        self.ActiveTest.setAccessibleDescription("")
        self.ActiveTest.setText("")
        self.ActiveTest.setIndent(10)
        self.ActiveTest.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.ActiveTest.setObjectName("ActiveTest")
        self.gridLayout.addWidget(self.ActiveTest, 0, 0, 1, 1)
        self.ButtonPanel = QtWidgets.QGroupBox(self.MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.ButtonPanel.sizePolicy().hasHeightForWidth())
        self.ButtonPanel.setSizePolicy(sizePolicy)
        self.ButtonPanel.setMinimumSize(QtCore.QSize(600, 80))
        self.ButtonPanel.setTitle("")
        self.ButtonPanel.setObjectName("ButtonPanel")
        self.ButtonPanelLayout = QtWidgets.QGridLayout(self.ButtonPanel)
        self.ButtonPanelLayout.setObjectName("ButtonPanelLayout")
        self.ButtonLayout = QtWidgets.QHBoxLayout()
        self.ButtonLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.ButtonLayout.setContentsMargins(100, -1, 100, -1)
        self.ButtonLayout.setSpacing(80)
        self.ButtonLayout.setObjectName("ButtonLayout")
        self.Button_1 = QtWidgets.QPushButton(self.ButtonPanel)
        self.Button_1.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_1.sizePolicy().hasHeightForWidth())
        self.Button_1.setSizePolicy(sizePolicy)
        self.Button_1.setText("")
        self.Button_1.setCheckable(False)
        self.Button_1.setDefault(False)
        self.Button_1.setFlat(False)
        self.Button_1.setObjectName("Button_1")
        self.ButtonLayout.addWidget(self.Button_1)
        self.Button_2 = QtWidgets.QPushButton(self.ButtonPanel)
        self.Button_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_2.sizePolicy().hasHeightForWidth())
        self.Button_2.setSizePolicy(sizePolicy)
        self.Button_2.setText("")
        self.Button_2.setObjectName("Button_2")
        self.ButtonLayout.addWidget(self.Button_2)
        self.Button_3 = QtWidgets.QPushButton(self.ButtonPanel)
        self.Button_3.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_3.sizePolicy().hasHeightForWidth())
        self.Button_3.setSizePolicy(sizePolicy)
        self.Button_3.setText("")
        self.Button_3.setObjectName("Button_3")
        self.ButtonLayout.addWidget(self.Button_3)
        self.ButtonPanelLayout.addLayout(self.ButtonLayout, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.ButtonPanel, 2, 0, 1, 1)
        self.ImageView = QtWidgets.QGraphicsView(self.MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.ImageView.sizePolicy().hasHeightForWidth())
        self.ImageView.setSizePolicy(sizePolicy)
        self.ImageView.setMinimumSize(QtCore.QSize(600, 400))
        self.ImageView.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ImageView.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.ImageView.setAcceptDrops(False)
        self.ImageView.setToolTip("")
        self.ImageView.setStatusTip("")
        self.ImageView.setWhatsThis("")
        self.ImageView.setAccessibleName("")
        self.ImageView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ImageView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ImageView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.ImageView.setObjectName("ImageView")
        self.gridLayout.addWidget(self.ImageView, 1, 0, 1, 1)
        self.Events = QtWidgets.QTextEdit(self.MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.Events.sizePolicy().hasHeightForWidth())
        self.Events.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(9)
        self.Events.setFont(font)
        self.Events.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.Events.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Events.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Events.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Events.setLineWidth(1)
        self.Events.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.Events.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.Events.setAutoFormatting(QtWidgets.QTextEdit.AutoNone)
        self.Events.setDocumentTitle("")
        self.Events.setUndoRedoEnabled(False)
        self.Events.setReadOnly(True)
        self.Events.setAcceptRichText(False)
        self.Events.setCursorWidth(1)
        self.Events.setObjectName("Events")
        self.gridLayout.addWidget(self.Events, 3, 0, 1, 1)
        self.ProgressBar = QtWidgets.QProgressBar(self.MainWindow)
        self.ProgressBar.setToolTip("")
        self.ProgressBar.setStatusTip("")
        self.ProgressBar.setWhatsThis("")
        self.ProgressBar.setAccessibleName("")
        self.ProgressBar.setAccessibleDescription("")
        self.ProgressBar.setProperty("value", 0)
        self.ProgressBar.setTextVisible(False)
        self.ProgressBar.setObjectName("ProgressBar")
        self.gridLayout.addWidget(self.ProgressBar, 4, 0, 1, 1)
        FixateUI.setCentralWidget(self.MainWindow)

        self.retranslateUi(FixateUI)
        QtCore.QMetaObject.connectSlotsByName(FixateUI)

    def retranslateUi(self, FixateUI):
        pass

